* .emacs.d

If you want, you can copy my Emacs init! But, honestly, there are
better ones out there:

- https://github.com/jhamrick/emacs/tree/master/.emacs.d

My setup is most likely to be of interest to R and Python users doing
data science. If you want to see how to best setup Emacs to do
enterprise Java, you have come to the wrong place.

Disclaimer: Although I try to update this, this  may or may not be
exactly what I am using today. And it may or may not eat your kittens
if you try to run it. That said, I think it works nicely.

Also, this config may or may not work perfectly on Windows. I do
sometimes use Emacs on Windows and shoehorn this beautiful tool into
the Win32 environment, but it is rarely pretty. I don't have a OSX
system, so I cannot test it there. But it works well for me on Fedora.

** Description of Contents

Broadly, this repo is divided into two parts. The init.el file in the
.emacs.d folder (where this README file is located) and everything
hiding in the lisp folder. The init.el is, of course, the
director. But almost all of the actual work takes place in the files
located in the lisp folder. With only one or two exceptions, files in
the lisp folder are mode-specific. Exceptions to this include
appearance, edit,  misc, proxy, and any other file which does not
contain "-config" in the filename.

In the listing below, if the file-name doesn't have a description, it
is a file with settings for the emacs mode of that name (minus -config).

- init.el: The director of the band.
- lisp/
  - appearance.el: Settings for how Emacs looks, incuding theme.
  - comint-config.el
  - dired-config.el
  - edit.el: Editor settings (tabs, spaces, etc.)
  - eimp-config.el
  - ein-config.el
  - elpy-config.el
  - emmet-config.el
  - epa-config.el
  - eshell-config.el
  - ess-config.el
  - flx-config.el
  - ido-config.el
  - magit-config.el
  - markdown-config.el
  - misc.el: Some custom functions, and anything else that doesn't fit
    in some other place.
  - orgmode-config.el
  - package-config.el
  - perspective-config.el
  - polymode-config.el
  - projectile-config.el
  - proxy.el
  - python-config.el
  - speedbar-config.el
  - sql-config.el
  - tabbar-config.el
  - web-config.el
  - yaml-config.el
  - yasnippet-config.el
- sql-connections.el: Sorry. No passwords here and the IP Addresses
  are internal only.

** Setup

*** Fedora Setup

The following bash code does 3 things:

1. Installs emacs and a few extra packages (requires sudo / password).
2. Changes to the user's home directory.
3. Clones this repo to the user's home directory, into the .emacs.d
   folder.

#+begin_src sh exports:code
  ## Installs emacs and a few extra packages I like.
  sudo dnf install \
     emacs-auctex.noarch emacs-auctex-doc.noarch \
     emacs-auto-complete.noarch \
     emacs-ess.noarch emacs-ess-doc.noarch\
     emacs-goodies.noarch \
     emacs-magit.noarch \
     python-ropemacs.noarch \
     emacs-slime-el.noarch \
     emacs-yaml-mode.noarch \
     emacs.x86_64

  ## Change to user's home directory, and then clones this repo.
  ## I assume git cli is already installed.
  cd ~
  git clone git@github.com:Choens/.emacs.d.lin.git .emacs.d
  emacs -q -l ~/.emacs.d init-first.el
#+end_src

*** Ubuntu Setup

I no longer use Ubuntu. The code below worked for me at one point, but
I no longer test/update it. It is included for
informational/historical purposes.

The following bash code does 3 things.

1. Installs emacs / emacs-goodies.
2. Changes to the user's home directory.
3. Clones this repo to the user's home directory, into the .emacs.d
   folder.

#+begin_src sh exports:code

  ## Installs emacs.
  sudo apt-get install emacs24 emacs-goodies-el git

  ## Change to user's home directory, and then clones this repo.
  ## I assume git cli is already installed.
  cd ~
  git clone git@github.com:Choens/.emacs.d.lin.git .emacs.d
  emacs -q -l ~/.emacs.d init-first.el
#+end_src
