* .emacs.d.lin

My emacs configuration for linux desktop systems. I am currently
using two different Kubuntu installations, and I use this to sync
emacs config changes between them.

** Description of Contents

This emacs configuration contains the following:

  - init.el
  - init-first.el
  - lisp/
    - key-bindings.el
    - misc.el
    - mode-specific-config.el
    - sql-connections.el

The contents of most of these files should be self-explanatory. If
you can't figure out what is in the key-bindings.el file, I really
don't think you are ready to install this.

The file misc.el contains random stuff that doesn't really seem to
fit anywhere else. The file sql-connections.el is a template of a
file I use (but can not share publicly for obvious reasons) to store
database passwords, making it easier to use SQL in emacs. Using this
file is NOT required, but you will want to comment out the following
line from mode-specific.el

#+begin_src lisp exports:code
  (load-file "~/config/sql-connections.el" ) 
#+end_src

This line appears on line 198 as of July, 2014.

A final, installed version of this system will also have the
following folders:

- backups/
- elpa/
- eshell/ (if you use it)

These folders are not tracked by the repo, as they are truly local
folders and do not belong as part of this project.

** Setup

Previous, overly complicated versions, of this emacs config involved
running several hundred lines of bash code. I am happy to report this
is not longer necessary. The following bash "scipt" does 4 things.

1. Installs emacs / emacs-goodies. This should work on ANY linux
   system using debian / ubuntu package names.
2. Changes to the user's home directory. Just in case.
3. Clones this repo to the user's home directory, in .emacs.d
4. Starts emacs, using the init-first.el file rather than
   init.el. This simplified init.el file is really the core of my
   personal settings, but relies only on those things that are either
   part of emacs by default or are brought in by installing
   emacs-goodies.

#+begin_src sh exports:code
  sudo apt-get install emacs24 emacs-goodies-el
  cd ~
  git clone git@github.com:Choens/.emacs.d.lin.git .emacs.d
  emacs -q -l ~/.emacs.d init-first.el
#+end_src

Then, install the following emacs extensions. Someday I'll automate
this last part.

- 
- 
- 

** Crazy Custom Andy Stuff

There are a series of custom lisp functions "open-" that define some
custom open commands, to make it easy for me to quickly open some
commonly used files. These may or may not be useful or relevant to
others. I intend to pull out all of the custom lisp and move it into a
file (or two) in the lisp folder to make it easier for someone else to
use this repo, without having to use all of my little weird
customizations.
