* README - .emacs.d.lin

My emacs configuration for Linux desktop systems. I use this
reposotiry to sync my Emacs configuration between multiple Kubuntu systems.

** Description of Contents

This emacs configuration contains the following:

  - init.el
  - init-first.el
  - lisp/
    - key-bindings.el
    - misc.el
    - mode-specific-config.el
    - sql-connections.el

The contents of most of these files will be self-explanatory to
experienced Emacs users.

_Things Worth Explaining_

- The file, misc.el, contains random stuff that doesn't really seem to
  fit anywhere else.
- The file, sql-connections.el, is a template of a file I use to store
  database passwords for sql-mode. This file is not necessary for
  everyone, but you will want to comment out the following
  line from mode-specific.el

** Setup

The following bash code ensures that a Linux system does 4 things.

1. Installs emacs / emacs-goodies. This should work on ANY linux
   system using debian / ubuntu package names.
2. Changes to the user's home directory.
3. Clones this repo to the user's home directory, into the .emacs.d
   folder.
4. Starts emacs, using the init-first.el file rather than
   init.el. This simplified init.el file is really the core of my
   personal settings, but relies only on those things that are either
   part of emacs by default or are brought in by installing
   emacs-goodies.

#+begin_src sh exports:code
  sudo apt-get install emacs24 emacs-goodies-el git
  cd ~
  git clone git@github.com:Choens/.emacs.d.lin.git .emacs.d
  emacs -q -l ~/.emacs.d init-first.el
#+end_src

Then, install the following emacs extensions. Someday I'll automate
this last part.

** Details

#+begin_src lisp exports:code
  (load-file "~/config/sql-connections.el" ) 
#+end_src

A final, installed version of this system will also have the
following folders:

- backups/
- elpa/
- eshell/ (if you use it)

These folders are not tracked by the repo, as they are truly local
folders and do not belong as part of this project.
