#!/bin/bash
# #############################################################################
# Setup Emacs
# 
# Description: Shell script to rapidly set up andy's emacs environment.
# 
# This file does the following:
# 1) Check to see if ~/.emacs.d exists. If not, create it.
# 2) Link init.el and lisp/ to ~/.emacs.d
# 3) Grab the latest version of sellout's solarized theme for emacs.
# 4) Byte compile everything.
#
#
# Dependencies
# - bash
# - git
# - emacs>=24, emacs-goodies.el
# #############################################################################

# -----------------------------------------------------------------------------
# Variables
# Change these to suit your setup.
# -----------------------------------------------------------------------------

# Source Files - Location of the git repo.
SourceDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SourceInit="$SourceDir/init.el"
SourceInitCompiled="$SourceDir/init.elc"
SourceLisp="$SourceDir/lisp"

# Destination Files
DestDir="/home/$USER/.emacs.d"
DestInit="$DestDir/init.el"
DestInitCompiled="$DestDir/init.elc"
DestLisp="$DestDir/lisp"

# -----------------------------------------------------------------------------
# Compile Lisp Files
# Although they aren't for
# -----------------------------------------------------------------------------
emacs --batch --eval '(byte-recompile-directory $SourceDir 0)'

# -----------------------------------------------------------------------------
# Check to see if ~/.emacs.d exists. If not, create it.
# -----------------------------------------------------------------------------
if [[ ! -e $DestDir ]]; then
    mkdir $DestDir
    mkdir $DestDir/sql
    echo "$DestDir created."
elif [[ -e $DestDir ]]; then
    echo "Error: $DestDir already exists."
    exit 99
fi

# -----------------------------------------------------------------------------
# Link Uncompiled Files / Folders
# -----------------------------------------------------------------------------

# -------------------------------------
# init.el
# -------------------------------------
if [[ ! -e $DestInit ]]; then  
    ln -s $SourceInit $DestInit
    echo "$DestInit linked."
elif [[ -e $DestInit ]]; then
    echo "Error: $DestInit already exists."
fi

# -------------------------------------
# init.elc
# -------------------------------------
if [[ ! -e $DestInitCompiled ]]; then  
    ln -s $SourceInitCompiled $DestInitCompiled
    echo "$DestInitCompiled linked."
elif [[ -e $DestInitCompiled ]]; then
    echo "Error: $DestInitCompiled already exists."
fi


# -------------------------------------
# lisp folder
# -------------------------------------
#if [[ ! -e $DestLisp ]]; then
#    mkdir $DestLisp
#    echo "$DestLisp created."
#    cd $SourceLisp
#    
#    for i in *.el
#    do
#        ln -s $SourceLisp/$i $DestLisp/$i
#	echo "$DestLisp/$i linked."
#    done
#elif [[ -e $DestLisp ]]; then
#    echo "Warning: $DestLisp already exists."
#fi
ln -s $SourceLisp $DestLisp


# -----------------------------------------------------------------------------
# Install solarized theme from GitHub
# Note - If you have your own fork, you will need to edit the URLs below. 
#	 This script assumes sellout's repo is origin.
#
# -----------------------------------------------------------------------------
cd $DestDir
git clone https://github.com/sellout/emacs-color-theme-solarized.git solarized-theme
#git fetch origin
#git merge origin/master


# -----------------------------------------------------------------------------
# 4) Byte Compile init.el and everything in lisp.
# -----------------------------------------------------------------------------
emacs --batch --eval '(byte-recompile-directory "~/.emacs.d/" 0)'
